import json,csv,datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parent
sources=[
{'id':'R01','type':'review','year':2022,'title':'Gas source localization and mapping with mobile robots: A review','doi':'10.1002/rob.22109','source_url':'https://onlinelibrary.wiley.com/doi/full/10.1002/rob.22109','use':'Primary starting review for gas-sensing hardware, ground and aerial platforms, source localization, distribution mapping, and informative path planning.','limit':'Gas mapping needs spatial localization and a measurement model; onboard gas sensing alone does not demonstrate autonomous source localization.','read_scope':'Publisher abstract and selected platform/mapping/discussion sections'},
{'id':'R02','type':'review','year':2021,'title':'Low-Cost Outdoor Air Quality Monitoring and Sensor Calibration: A Survey and Critical Analysis','doi':'10.1145/3446005','source_url':'https://arxiv.org/abs/1912.06384','use':'Starting survey for low-cost air sensor calibration, cross-sensitivity, environmental effects, and drift.','limit':'Literature calibration methods do not provide calibration coefficients for the rover sensors.','read_scope':'Author preprint abstract and bibliographic record'},
{'id':'R03','type':'review','year':2020,'title':'A Review of Low-Cost Particulate Matter Sensors from the Developers’ Perspectives','doi':'10.3390/s20236819','source_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC7730878/','use':'Sensor-developer view of low-cost particulate monitoring and Plantower-family evaluations.','limit':'Treat calibration and comparison results as sensor-, aerosol-, and deployment-specific.','read_scope':'Indexed article excerpt; full page later returned an access challenge'},
{'id':'R04','type':'empirical_sensor_evaluation','year':2022,'title':'Low-cost monitoring of atmospheric PM—development and testing','doi':'10.1016/j.jenvman.2021.114158','source_url':'https://www.sciencedirect.com/science/article/pii/S0301479721022209','use':'Directly relevant PMS7003 evaluation involving controlled calibration and a 15-month field deployment.','limit':'Results belong to that study and must not be quoted as A3P5 accuracy, reliability, or maintenance validation.','read_scope':'Publisher abstract and highlights'},
{'id':'R05','type':'review','year':2021,'title':'Connected Sensors, Innovative Sensor Deployment and Intelligent Data Analysis for Online Water Quality Monitoring','doi':'10.1109/JIOT.2021.3081772','source_url':'https://researchportal.hw.ac.uk/en/publications/connected-sensors-innovative-sensor-deployment-and-intelligent-da/','use':'Overview linking water sensor parameters, deployment using autonomous platforms, and online data analysis.','limit':'A wheeled rover requires a specified sampling interface; aquatic-vehicle results are context rather than direct evidence for this chassis.','read_scope':'Author institution bibliographic record and abstract'},
{'id':'R06','type':'simulator_paper','year':2017,'title':'GADEN: A 3D Gas Dispersion Simulator for Mobile Robot Olfaction in Realistic Environments','doi':'10.3390/s17071479','source_url':'https://github.com/MAPIRlab/gaden','use':'Reproducible gas-dispersion and gas-sensor simulation framework for future navigation and olfaction experiments.','limit':'A simulator supports controlled algorithm comparisons; it does not validate physical sensor response or field performance.','read_scope':'Official project README and supplied citation'},
{'id':'R07','type':'simulation_dataset','year':2023,'title':'VGR Dataset: A CFD-based Gas Dispersion Dataset for Mobile Robotic Olfaction','doi':'10.1007/s10846-023-02012-z','source_url':'https://mapir.isa.uma.es/mapirwebsite/?p=1708','use':'Author-provided dataset page describes 120 airflow/gas simulations across 30 detailed house models, with GADEN/OpenFOAM files.','limit':'These are simulated indoor data; they are neither outdoor emissions observations nor measurements collected by A3P5.','read_scope':'Official dataset page and citation'},
{'id':'R08','type':'experimental_sensor_dataset','year':2012,'title':'Gas Sensor Array Drift Dataset','doi':'10.24432/C5RP6W','source_url':'https://archive.ics.uci.edu/dataset/224/gas','use':'Controlled metal-oxide sensor-array benchmark for drift and calibration-transfer methods.','limit':'Different sensors and controlled exposure conditions prevent direct transfer of reported model accuracy to MQ135/MQ7/MQ4 devices.','read_scope':'Official UCI dataset metadata and variable description'},
{'id':'R09','type':'field_sensor_dataset','year':2008,'title':'Air Quality','doi':'10.24432/C59K5F','source_url':'https://archive.ics.uci.edu/dataset/360/air+quality','use':'UCI reports 9,358 hourly records from five metal-oxide sensors with reference gas measurements; useful for future calibration-method examples.','limit':'Different equipment and location from the rover. Preserve time order in validation and handle the documented -200 missing-value marker.','read_scope':'Official UCI dataset metadata and variable description'},
{'id':'R10','type':'experimental_sensor_dataset','year':2015,'title':'Gas sensor array under dynamic gas mixtures','doi':'10.24432/C5WP4C','source_url':'https://archive.ics.uci.edu/dataset/322/gas+sensor+array+under+dynamic+gas+mixtures','use':'UCI reports continuous recordings from 16 Figaro sensors under varying methane/ethylene and CO/ethylene mixtures; useful for response-delay and cross-sensitivity methods.','limit':'Not MQ-series hardware or a rover field benchmark. The page contains a legacy research-only note alongside a CC BY 4.0 label; resolve terms before reuse beyond this bibliographic recommendation.','read_scope':'Official UCI dataset metadata and variable description'},
{'id':'R11','type':'simulator_paper','year':2025,'title':'Gaden-RT: A Real Time and Interactive Gas Dispersion Simulator for Mobile Robotics','doi':'10.1016/j.softx.2025.102388','source_url':'https://github.com/MAPIRlab/gaden','use':'Current official GADEN project citation for the real-time interactive simulator implementation.','limit':'Cite the version actually used if future experiments adopt it; no such experiments were performed here.','read_scope':'Official project README and supplied citation'},
]
for s in sources:
    s['doi_url']='https://doi.org/'+s['doi'];s['checked_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();s['relationship_to_census']='separate source-checked contextual lead; census membership checked only after retrieval finishes'
(ROOT/'context_sources.json').write_text(json.dumps(sources,indent=2,ensure_ascii=False),encoding='utf-8')
with (ROOT/'context_sources.csv').open('w',newline='',encoding='utf-8-sig') as f:
    w=csv.DictWriter(f,fieldnames=list(sources[0]));w.writeheader();w.writerows(sources)
lines=['# Source-checked context and future benchmark options','','These 11 leads supplement the metadata census. They were checked at the scope stated below, not all read in full. None demonstrates this rover’s performance. Datasets were identified, not downloaded or tested.','']
for s in sources:
    lines += [f"## {s['id']} · {s['title']} ({s['year']})",'',f"Type: {s['type']}. DOI: [{s['doi']}]({s['doi_url']}). [Checked source]({s['source_url']}).",'',s['use'],'',f"Application limit: {s['limit']}",'',f"Read scope: {s['read_scope']}.",'']
(ROOT/'context_sources.md').write_text('\n'.join(lines),encoding='utf-8')
print('Saved',len(sources),'source-checked contextual leads')
